services:
  postgres:
    image: postgres:15-alpine
    container_name: finpilot_db
    environment:
      POSTGRES_DB: finpilot
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"